name = "DMF"
uuid = "8da5501e-5835-5062-9a0c-bca364f45b2c"
keywords = ["DMD", "DMF", "Time Series"]
license = "Apache 2.0"
desc = "Dynamic Mode Factorization."
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
QuantEcon = "fcd29c91-0bd7-5a09-975d-7ac3f643a60c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
WAV = "8149f6b0-98f6-5db9-b78f-408fbbb8ef88"
