name = "DMF"
uuid = "8da5501e-5835-5062-9a0c-bca364f45b2c"
keywords = ["DMD", "DMF", "Time Series"]
license = "Apache 2.0"
desc = "Dynamic Mode Factorization."
version = "0.1"

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuantEcon = "fcd29c91-0bd7-5a09-975d-7ac3f643a60c"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
